version: "3.8"
services:
  web:
    build: ./app
    image: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 156890423810.dkr.ecr.us-west-2.amazonaws.com/workshop:workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=Endpointnctutorials.c5setcjdwzh1.us-west-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-35-165-170-175.us-west-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 156890423810.dkr.ecr.us-west-2.amazonaws.com/workshop2:workshop2_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: